# Generated by Django 5.0.7 on 2024-07-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('In-Transit', 'In-Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Refunded', 'Refunded'), ('Failed', 'Failed'), ('Delayed', 'Delayed')], default='Processing', max_length=10),
        ),
    ]
